### ISSUE TITLE
Using pool.drain on exit

### ISSUE THREAD

**Issue by TuningGuide** [NatalieWolfe/node-promise-pool#3]
Hi, thanks for the work. Do you know how to exactly use pool.drain on node exit?
Because on https://nodejs.org/api/process.html#process_event_exit it is written that you should not use asynchronous call within exit. But drain returns a promise and is therefore asynchronous, or?

**Comment by NatalieWolfe** [comment]
Hi! Glad you like the package.

At the point where the process `exit` event has been fired the application is going to exit immediately, and any open connections will be forcefully closed. Unfortunately there is no way that the pool can guarantee safe destruction of all of its resources synchronously because some of them may be acquired at the time of exit, and the [factory `destroy`][1] method you provide may be asynchronous.

If your factory `destroy` method is synchronous and you just want to gracefully clean up as much as possible, you can use [`PromisePool#destroyAllNow`][2] to destroy all currently-available (e.g. unacquired) resources. While it returns a promise, it does call destroy for all available resources synchronously, thus if `destroy` is synchronous, this method is synchronous. Here is a little demo of this: https://tonicdev.com/wolfe/57126939a0a8bc180017b026

That all being said, [`PromisePool#drain`][3] is the better method to use, but you will need to call it _before_ you get the process exit stage. If you are writing a server, I recommend putting it in a `close` event handler for your server like this:

```js
var pool = promisePool.create({ /* ... */ });
var server = createMyAwesomeServer();

server.on('close', function(){
    pool.drain();
});
```

[1]: http://nataliewolfe.github.io/node-promise-pool/docs/PromisePool.Factory.html
[2]: http://nataliewolfe.github.io/node-promise-pool/docs/PromisePool.html#destroyAllNow
[3]: http://nataliewolfe.github.io/node-promise-pool/docs/PromisePool.html#drain

**Comment by TuningGuide** [comment]
Thank you, but I use node as process and kill it with strg+c so I have following right now:

```
pools.mongoose = pool.create({
	name    : 'mongoose',
	max     : 1,
	min     : 1,
	create  : function(){
		var options = { promiseLibrary: Promise };
		return mongoose.connect(config.mongo, options);
	},
	destroy : function(db){
		return db.close();
	}
});

cleanup(function () {
	var drains = Object.keys(pools).map(function (key) {
		return pools[key].drain().then(function (msg) {
			ServerLog(key+'... connection drained', msg);
		});
	})

	Promise.all(drains).then(function () {
		ServerLog('All connections drained.');
	}).catch(ServerError);
});

...
process.on('exit', function () {
		process.emit('cleanup');
	});

	// catch ctrl+c event and exit normally
	process.on('SIGINT', function () {
		console.log('Ctrl-C...');
		process.exit(2);
	});
```

**Comment by NatalieWolfe** [comment]
Ah, then I would recommend doing a graceful shutdown on Ctrl+C, something like this:

```js
var sigintCount = 0;
process.on('SIGINT', function() {
    ++sigintCount;
    if (sigintCount == 1) {
        console.log('Gracefully stopping, press ^C again to force exit.');
        process.emit('cleanup');
    }
    else {
        console.log('Force stopping.');
        process.exit(2);
    }
});
```

I am assuming that you have hooks on the `cleanup` event you emit which will stop all your tasks and drain the pools. If you do, then the process will exit once those have all stopped and there are no more open connections or tasks on the event loop.

**Comment by TuningGuide** [comment]
Your assumptions are right and the double Ctrl+C sounds perfekt. Thanks

**Comment by NatalieWolfe** [comment]
Awesome. Let me know how it goes or if there is any way I can help! :)

**Comment by NatalieWolfe** [comment]
Just realized this ticket was still open and it sounds like your issue was resolved so I am going to close it. If you still have any questions let me know!
